name: Test

on:
  workflow_dispatch:
    inputs:
      FLAVOUR:
        required: true
        type: string
        default: "production"

jobs:
  build:
    environment: ${{inputs.FLAVOUR}}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Length of the secret: ${#SECRET_TEST} characters."
        env:
          SECRET_TEST: ${{ secrets.SENTRY_DSN }}
      - run: |
          echo "Length of the secret: ${#SECRET_TEST} characters."
        env:
          SECRET_TEST: ${{ secrets.FIREBASE_APP_CHECK }}
      - run: |
          echo "Length of the secret: ${#SECRET_TEST} characters."
        env:
          SECRET_TEST: ${{ secrets.FIREBASE_VAPID_KEY }}